OnlineSchool/Models/Lesson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineSchool.Models
{
    public class Lesson
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual LessonType Type { get; set; }
        public string Level { get; set; }
        public string Year { get; set; }
        public string Term { get; set; }

    }
}

OnlineSchool/Models/LessonType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineSchool.Models
{
    public class LessonType
    {
        public int Id { get; set; }
        [Display(Name ="Type")]
        public string Name { get; set; }

    }
}

OnlineSchool/Controllers/LessonController.cs
using OnlineSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineSchool.Controllers
{
    public class LessonController : Controller
    {
        private ApplicationDbContext _context;

        public LessonController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Lesson
        [HttpGet]
        [Authorize(Roles = "Admins")]
        public ActionResult Index()
        {
            var lessons = _context.Lessons.ToList();
            return View("Index", lessons);

        }


        [Authorize(Roles = "Admins")]
        public ActionResult New()
        {

            var lesson = new Lesson();
            return View("New", lesson);
        }

    }
}

OnlineSchool/Controllers/PriestController.cs
using OnlineSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineSchool.Controllers
{
    public class PriestController : Controller
    {
        private ApplicationDbContext _context;

        public PriestController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Priest
        [HttpGet]
        [Authorize(Roles = "Admins")]
        public ActionResult Index()
        {
            var priests = _context.Priests.ToList();
            
            return View("Index", priests);
        }


        [Authorize(Roles = "Admins")]
        public ActionResult New()
        {

            var priest = new Priest();
           

            return View("New", priest);
        }

        [HttpPost]
        [Authorize(Roles = "Admins")]
        public ActionResult Save(Priest priest)
        {
            var priestChurch = _context.Churches.SingleOrDefault(c => c.Name == priest.Church.Name);


            if (!ModelState.IsValid)
            {
                return View("New", priest);
            }



            if (priest.Id == 0)
            {

                var newPriest = new Priest
                {
                    Name = priest.Name,
                    MobileNumber = priest.MobileNumber,
                    OfficeNumber = priest.OfficeNumber,
                    Church = priestChurch




                };
                _context.Priests.Add(newPriest);


            }
            else
            {
                var existingPriest = _context.Priests.SingleOrDefault(c => c.Id == priest.Id);

                existingPriest.Name = priest.Name;
                existingPriest.MobileNumber = priest.MobileNumber;
                existingPriest.OfficeNumber = priest.OfficeNumber;
                existingPriest.Church = priestChurch;


            }


            _context.SaveChanges();

            return RedirectToAction("Index");


        }

        [Authorize(Roles = "Admins")]
        public ActionResult Edit(int id)
        {


            var priest = new Priest();
           

            priest = _context.Priests.SingleOrDefault(c => c.Id == id);

            if (priest == null)
                return HttpNotFound();




            return View("New", priest);



        }



        [Authorize(Roles = "Admins")]
        public ActionResult Delete(int id)
        {
            var priest = new Priest();
            

            priest= _context.Priests.SingleOrDefault(c => c.Id == id);

            if (priest == null)
                return HttpNotFound();

            _context.Priests.Remove(priest);
            _context.SaveChanges();


            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Admins")]
        public ActionResult Details(int id)
        {
            var priest = _context.Priests.SingleOrDefault(c => c.Id == id);

            priest.Church = _context.Churches.SingleOrDefault(p => p.Id == priest.Church.Id);



            return View("Details", priest);
        }
    }
}

OnlineSchool/Views/Lesson/Index.cshtml
@model IEnumerable<OnlineSchool.Models.Lesson>

@{
    ViewBag.Title = "Lessons";
}


<h2 class="text-center">List of Lessons</h2>

<p class="float-right">
    @Html.ActionLink("Add new Lesson", "New", "Lesson", new { @class = "btn btn-warning" })

</p>

@if (Model.Count() == 0)
{
    <p class="text-danger">We don't currently have any Lessons yet</p>
}
<table class="table table-bordered table-hover">
    <thead class="thead-light text-center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Level)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Level)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Priest", new { id = item.Id }, new { @class = "btn btn-success" })
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Priest", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

</table>

OnlineSchool/Views/Lesson/New.cshtml
@model OnlineSchool.Models.Lesson
@using OnlineSchool.Models


@if (Model.Id == 0)
{
    ViewBag.Title = "New";
}
else
{
    ViewBag.Title = "Edit";
}

@if (Model.Id == 0)
{
    <h2>New Lesson</h2>
}
else
{
    <h2>@Model.Name</h2>
}

@using (Html.BeginForm("Save", "Lesson"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-row">

            <div class="form-group col-md-4">
                @Html.LabelFor(model => model.Level, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Level, new List<SelectListItem> {

                        new SelectListItem { Value = "Pre-Level 1" , Text = "Pre-Level 1" },
                        new SelectListItem { Value = "Pre-Level 2" , Text = "Pre-Level 2" },
                        new SelectListItem { Value = "Level 1" , Text = "Level 1" },
                        new SelectListItem { Value = "Level 2" , Text = "Level 2" },
                        new SelectListItem { Value = "Level 3" , Text = "Level 3" },
                        new SelectListItem { Value = "Level 4" , Text = "Level 4" },
                     }, "Select Level",
                    new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-4">
                @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Year, new List<SelectListItem> {

                        new SelectListItem { Value = "First Year" , Text = "First Year" },
                        new SelectListItem { Value = "Second Year" , Text = "Second Year" },
                     }, "Select Year",
                    new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-4">
                @Html.LabelFor(model => model.Term, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Term, new List<SelectListItem> {

                        new SelectListItem { Value = "First Term" , Text = "First Term" },
                        new SelectListItem { Value = "Second Term" , Text = "Second Term" },
                        new SelectListItem { Value = "Third Term" , Text = "Third Term" },
                     }, "Select Term",
                    new { @class = "form-control" } )
                    @Html.ValidationMessageFor(model => model.Term, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Type.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type.Name, new List<SelectListItem> {

                      new SelectListItem { Value = "Coptic" , Text = "Coptic" },
                      new SelectListItem { Value = "Rite" , Text = "Rite" },
                      new SelectListItem { Value = "Tune" , Text = "Tune" },
                   }, "Select Type",
                  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Type.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}