OnlineSchool/Models/Servant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using OnlineSchool.ValidationAttributes;

namespace OnlineSchool.Models
{
    public class Servant
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Card Code")]
        [ServantCodeCheck]
        public string Code { get; set; }
        
        [Required]
        public string Name { get; set; }

        [EmailAddress]
        [Required]
        public string Email { get; set; }

        public virtual Class Class { get; set; }
        

        public virtual ApplicationUser ApplicationUser { get; set; }

    }
}

OnlineSchool/Controllers/ServantController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using OnlineSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineSchool.Controllers
{
    public class ServantController : Controller
    {

        private ApplicationDbContext _context;

        public ServantController()
        {
            _context = new ApplicationDbContext();
        }


        // GET: Servant
        [HttpGet]
        [Authorize(Roles = "Admins")]
        public ActionResult Index()
        {
            var servants = _context.Servants.ToList();
            return View("Index", servants);
        }

        [Authorize(Roles = "Admins")]
        public ActionResult New()
        {

            var servant = new Servant();
            return View("New", servant);
        }


        [HttpPost]
        [Authorize(Roles = "Admins")]
        public ActionResult Save(Servant servant)
        {


            if (!ModelState.IsValid)
            {
                return View("New", servant);
            }



            if (servant.Id == 0)
            {

                var newServant = new Servant
                {
                    Code = servant.Code,
                    Name = servant.Name,
                    Email = servant.Email,





            };
                    var User = _context.Users.SingleOrDefault(u => u.Email == servant.Email);
                    var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_context));
                    UserManager.AddToRole(User.Id, "Admins");

                _context.Servants.Add(newServant);


            }
            else
            {
                var existingServant = _context.Servants.SingleOrDefault(c => c.Id == servant.Id);

                existingServant.Code = servant.Code;
                existingServant.Name = servant.Name;
                existingServant.Email = servant.Email;


            }


            _context.SaveChanges();

            return RedirectToAction("Index");


        }

        [Authorize(Roles = "Admins")]
        public ActionResult Edit(int id)
        {


            var servant = new Servant();
           

            servant = _context.Servants.SingleOrDefault(c => c.Id == id);

            if (servant == null)
                return HttpNotFound();




            return View("New", servant);



        }

        [Authorize(Roles = "Admins")]
        public ActionResult Delete(int id)
        {
            var servant = new Servant();
           

            servant = _context.Servants.SingleOrDefault(c => c.Id == id);

            var User = _context.Users.SingleOrDefault(u => u.Email == servant.Email);
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_context));
            UserManager.RemoveFromRole(User.Id, "Admins");

            if (servant == null)
                return HttpNotFound();
            _context.Servants.Remove(servant);
            _context.SaveChanges();


            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Admins")]
        public ActionResult Details(int id)
        {
            var servant = _context.Servants.SingleOrDefault(c => c.Id == id);

           

            return View("Details", servant);
        }
    }
}

OnlineSchool/Views/Servant/Details.cshtml
@model OnlineSchool.Models.Servant

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name</h2>

<div>
    <h4>Servant Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index", "Servant", new { @class = "btn btn-dark" }) ||
    @Html.ActionLink("Edit Servant", "Edit", "Servant", new { id = Model.Id }, new { @class = "btn btn-success" })
</p>

OnlineSchool/Views/Servant/Index.cshtml
@model IEnumerable<OnlineSchool.Models.Servant>

@{
    ViewBag.Title = "Servants";
}

<h2 class="text-dark text-center">List of Servants</h2>

<p class="float-right">
    @Html.ActionLink("Add new servant", "New", "Servant", new { @class = "btn btn-warning" })
</p>
@if (Model.Count() == 0)
{
    <p class="text-danger">We don't currently have any servants yet</p>
}
<table class="table table-bordered table-hover">
    <thead class="thead-light text-center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Class.Name)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Servant", new { id = item.Id }, new { @class = "btn btn-success" })
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "Servant", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
        }

</table>

OnlineSchool/Views/Servant/New.cshtml
@model OnlineSchool.Models.Servant

@using OnlineSchool.Models


@if (Model.Id == 0)
{
    ViewBag.Title = "New";
}
else
{
    ViewBag.Title = "Edit";
}

@if (Model.Id == 0)
{
    <h2>New Servant</h2>
}
else
{
    <h2>@Model.Name</h2>
}
@using (Html.BeginForm("Save", "Servant"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Servant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.Id == 0)
        {
            <div class="form-group flex-column">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">

                    @using (var db = new ApplicationDbContext())
                    {
                        @Html.DropDownListFor(model => model.Email, new SelectList(db.Users.Where(u => !db.Students.Any(u2 => u2.Email == u.Email) && !db.Servants.Any(u2 => u2.Email == u.Email)), "Email", "Email"), "Select Servant Email", new { @class = "form-control" })
                    }

                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                </div>
            </div>
        }
        else
        {
            <div class="form-group flex-column">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">

                    @using (var db = new ApplicationDbContext())
                    {
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @readonly = "readonly" })
                    }

                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                </div>
            </div>

        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
    @Html.HiddenFor(model => model.Id)


}