OnlineSchool/ViewModels/ClassViewModel.cs
using OnlineSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineSchool.ViewModels
{
    public class ClassViewModel
    {
        public int Id { get; set; }
        //[Required]
        public string Name { get; set; }

        public IEnumerable<MultiSelectList> Lessons { get; set; }
        public IEnumerable<SelectListItem> Students { set; get; } 
        public string[] SelectedStudents { set; get; }
        public IEnumerable<MultiSelectList> Servants { get; set; }
    }
}

OnlineSchool/Controllers/ClassController.cs
using OnlineSchool.Models;
using OnlineSchool.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineSchool.Controllers
{
    public class ClassController : Controller
    {
        private ApplicationDbContext _context;

        public ClassController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Church
        [HttpGet]
        [Authorize(Roles = "Admins")]
        public ActionResult Index()
        {
            var classes = _context.Classes.ToList();
            return View("Index", classes);

        }

        
        [Authorize(Roles = "Admins")]
        public ActionResult New()
        {

            var classViewModel = new ClassViewModel();

            var studentslist = _context.Students.Select(s => s.Name).ToList();
            classViewModel.Students = new SelectList(studentslist);
            return View("New", classViewModel);
        }



    }
}

OnlineSchool/Views/Class/Index.cshtml
@model IEnumerable<OnlineSchool.Models.Class>

@{
    ViewBag.Title = "Classes";
}

<h2 class="text-dark text-center">List of Classes</h2>

<p class="float-right">
    @Html.ActionLink("Add new Class", "New", "Class", new { @class = "btn btn-warning" })
</p>
@if (Model.Count() == 0)
{
    <p class="text-danger">We don't currently have any Classes yet</p>
}
<table class="table table-bordered table-hover">
    <thead class="thead-light text-center">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lessons)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Servants)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Students)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lessons.Count())
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Servants.Count())
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Students.Count())
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Servant", new { id = item.Id }, new { @class = "btn btn-success" })
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "Servant", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
        }

</table>

OnlineSchool/Views/Class/New.cshtml
@model OnlineSchool.ViewModels.ClassViewModel



@if (Model.Id == 0)
{
    ViewBag.Title = "New";
}
else
{
    ViewBag.Title = "Edit";
}

@if (Model.Id == 0)
{
    <h2>New Class</h2>
}
else
{
    <h2>@Model.Name</h2>
}
@using (Html.BeginForm("Save", "Class"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Students, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.ListBoxFor(s=>s.SelectedStudents, Model.Students,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Students, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>

    @Html.HiddenFor(model => model.Id)


}